openapi: 3.0.2
info:
  title: Mazewire External API
  version: 0.1.0
paths:
  /:
    get:
      summary: List API versions
      responses:
        "200":
          description: Returns a list of the versions of the API available
  /content:
    get:
      summary: List content
      responses: 
        "200":
          description: Returns a list of the content objects selected
  /users:
    get:
      summary: List users
      responses:
        "200":
          description: Returns a list of the users selected
    post:
      summary: Create a user
      responses:
        "200":
          description: Created a user with the basic details given
        "400":
          description: The request could not be accepted with the data given
  /users/self:
    get:
      summary: Shows current user
      responses:
        "200":
          description: Returns details of the user identified from the authentication token
  /users/{id}:
    get:
      summary: Shows current user
      parameters:
        - name: id
          in: path
          description: The ID of the user to retrieve
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Returns details of the user identified from the authentication token
  /media:
    get:
      summary: List media metadata
      responses:
        "200":
          description: Returns a list of the media metadata objects selected
