// Code generated by protoc-gen-go. DO NOT EDIT.
// source: types/plugins_list/list.proto

package plugins_list

import (
	fmt "fmt"
	internal "github.com/dchenk/mazewire/pkg/plugins/internal"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// A Status describes the status of a plugin registered with the main system or site.
type Status int32

const (
	Status_INACTIVE Status = 0
	Status_ACTIVE   Status = 1
)

var Status_name = map[int32]string{
	0: "INACTIVE",
	1: "ACTIVE",
}

var Status_value = map[string]int32{
	"INACTIVE": 0,
	"ACTIVE":   1,
}

func (x Status) String() string {
	return proto.EnumName(Status_name, int32(x))
}

func (Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_40c67918e7640e6b, []int{0}
}

// A PluginsList contains a list of Identifier objects along with the status of each plugin.
type PluginsList struct {
	List                 []*PluginsList_Listing `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *PluginsList) Reset()         { *m = PluginsList{} }
func (m *PluginsList) String() string { return proto.CompactTextString(m) }
func (*PluginsList) ProtoMessage()    {}
func (*PluginsList) Descriptor() ([]byte, []int) {
	return fileDescriptor_40c67918e7640e6b, []int{0}
}

func (m *PluginsList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PluginsList.Unmarshal(m, b)
}
func (m *PluginsList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PluginsList.Marshal(b, m, deterministic)
}
func (m *PluginsList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PluginsList.Merge(m, src)
}
func (m *PluginsList) XXX_Size() int {
	return xxx_messageInfo_PluginsList.Size(m)
}
func (m *PluginsList) XXX_DiscardUnknown() {
	xxx_messageInfo_PluginsList.DiscardUnknown(m)
}

var xxx_messageInfo_PluginsList proto.InternalMessageInfo

func (m *PluginsList) GetList() []*PluginsList_Listing {
	if m != nil {
		return m.List
	}
	return nil
}

type PluginsList_Listing struct {
	Plugin               *internal.Registration `protobuf:"bytes,1,opt,name=plugin,proto3" json:"plugin,omitempty"`
	Status               Status                 `protobuf:"varint,2,opt,name=status,proto3,enum=pluginslist.Status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *PluginsList_Listing) Reset()         { *m = PluginsList_Listing{} }
func (m *PluginsList_Listing) String() string { return proto.CompactTextString(m) }
func (*PluginsList_Listing) ProtoMessage()    {}
func (*PluginsList_Listing) Descriptor() ([]byte, []int) {
	return fileDescriptor_40c67918e7640e6b, []int{0, 0}
}

func (m *PluginsList_Listing) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PluginsList_Listing.Unmarshal(m, b)
}
func (m *PluginsList_Listing) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PluginsList_Listing.Marshal(b, m, deterministic)
}
func (m *PluginsList_Listing) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PluginsList_Listing.Merge(m, src)
}
func (m *PluginsList_Listing) XXX_Size() int {
	return xxx_messageInfo_PluginsList_Listing.Size(m)
}
func (m *PluginsList_Listing) XXX_DiscardUnknown() {
	xxx_messageInfo_PluginsList_Listing.DiscardUnknown(m)
}

var xxx_messageInfo_PluginsList_Listing proto.InternalMessageInfo

func (m *PluginsList_Listing) GetPlugin() *internal.Registration {
	if m != nil {
		return m.Plugin
	}
	return nil
}

func (m *PluginsList_Listing) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_INACTIVE
}

func init() {
	proto.RegisterEnum("pluginslist.Status", Status_name, Status_value)
	proto.RegisterType((*PluginsList)(nil), "pluginslist.PluginsList")
	proto.RegisterType((*PluginsList_Listing)(nil), "pluginslist.PluginsList.Listing")
}

func init() { proto.RegisterFile("types/plugins_list/list.proto", fileDescriptor_40c67918e7640e6b) }

var fileDescriptor_40c67918e7640e6b = []byte{
	// 250 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2d, 0xa9, 0x2c, 0x48,
	0x2d, 0xd6, 0x2f, 0xc8, 0x29, 0x4d, 0xcf, 0xcc, 0x2b, 0x8e, 0xcf, 0xc9, 0x2c, 0x2e, 0xd1, 0x07,
	0x11, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0xdc, 0x50, 0x09, 0x90, 0x90, 0x94, 0x3c, 0x94,
	0xa3, 0x9f, 0x99, 0x57, 0x92, 0x5a, 0x94, 0x97, 0x98, 0x03, 0x67, 0x40, 0x54, 0x2b, 0xad, 0x66,
	0xe4, 0xe2, 0x0e, 0x80, 0xa8, 0xf1, 0xc9, 0x2c, 0x2e, 0x11, 0x32, 0xe1, 0x62, 0x01, 0x69, 0x94,
	0x60, 0x54, 0x60, 0xd6, 0xe0, 0x36, 0x52, 0xd0, 0x43, 0x32, 0x4c, 0x0f, 0x49, 0x9d, 0x1e, 0x88,
	0xc8, 0xcc, 0x4b, 0x0f, 0x02, 0xab, 0x96, 0x4a, 0xe3, 0x62, 0x87, 0x0a, 0x08, 0xe9, 0x71, 0xb1,
	0x41, 0xf4, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x1b, 0x89, 0xe9, 0xc1, 0x6d, 0x0c, 0x4a, 0x4d,
	0xcf, 0x2c, 0x2e, 0x29, 0x4a, 0x2c, 0xc9, 0xcc, 0xcf, 0x0b, 0x82, 0xaa, 0x12, 0xd2, 0xe6, 0x62,
	0x2b, 0x2e, 0x49, 0x2c, 0x29, 0x2d, 0x96, 0x60, 0x52, 0x60, 0xd4, 0xe0, 0x33, 0x12, 0x46, 0xb1,
	0x32, 0x18, 0x2c, 0x15, 0x04, 0x55, 0xa2, 0xa5, 0xc4, 0xc5, 0x06, 0x11, 0x11, 0xe2, 0xe1, 0xe2,
	0xf0, 0xf4, 0x73, 0x74, 0x0e, 0xf1, 0x0c, 0x73, 0x15, 0x60, 0x10, 0xe2, 0xe2, 0x62, 0x83, 0xb2,
	0x19, 0x9d, 0x8c, 0xa3, 0x0c, 0xd3, 0x33, 0x4b, 0x32, 0x4a, 0x93, 0xf4, 0x92, 0xf3, 0x73, 0xf5,
	0x53, 0x92, 0x33, 0x52, 0xf3, 0xb2, 0xf5, 0x73, 0x13, 0xab, 0x52, 0xcb, 0x33, 0x8b, 0x52, 0xf5,
	0x0b, 0xb2, 0xd3, 0xf5, 0x31, 0xc3, 0x2f, 0x89, 0x0d, 0x1c, 0x1a, 0xc6, 0x80, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xe0, 0x53, 0x18, 0x99, 0x5c, 0x01, 0x00, 0x00,
}
