// Code generated by protoc-gen-go. DO NOT EDIT.
// source: plugins/internal/internal.proto

package internal // import "github.com/dchenk/mazewire/pkg/plugins/internal"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import version "github.com/dchenk/mazewire/pkg/types/version"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// A Spec contains a single specification by a plugin.
// This type is needed separately from the Spec type in the specs package because here the value
// must be an actual string, not a fmt.Stringer.
type Spec struct {
	// Type is the type of specification defined in this PluginSpec.
	Type uint32 `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	// Value is the particular value for the spec type.
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Spec) Reset()         { *m = Spec{} }
func (m *Spec) String() string { return proto.CompactTextString(m) }
func (*Spec) ProtoMessage()    {}
func (*Spec) Descriptor() ([]byte, []int) {
	return fileDescriptor_internal_abdee2133d4c549b, []int{0}
}
func (m *Spec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Spec.Unmarshal(m, b)
}
func (m *Spec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Spec.Marshal(b, m, deterministic)
}
func (dst *Spec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Spec.Merge(dst, src)
}
func (m *Spec) XXX_Size() int {
	return xxx_messageInfo_Spec.Size(m)
}
func (m *Spec) XXX_DiscardUnknown() {
	xxx_messageInfo_Spec.DiscardUnknown(m)
}

var xxx_messageInfo_Spec proto.InternalMessageInfo

func (m *Spec) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *Spec) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

// A Handler is generated out of a hooks.Handler or filters.Handler.
type Handler struct {
	Specs                []*Spec  `protobuf:"bytes,1,rep,name=specs,proto3" json:"specs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Handler) Reset()         { *m = Handler{} }
func (m *Handler) String() string { return proto.CompactTextString(m) }
func (*Handler) ProtoMessage()    {}
func (*Handler) Descriptor() ([]byte, []int) {
	return fileDescriptor_internal_abdee2133d4c549b, []int{1}
}
func (m *Handler) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Handler.Unmarshal(m, b)
}
func (m *Handler) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Handler.Marshal(b, m, deterministic)
}
func (dst *Handler) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Handler.Merge(dst, src)
}
func (m *Handler) XXX_Size() int {
	return xxx_messageInfo_Handler.Size(m)
}
func (m *Handler) XXX_DiscardUnknown() {
	xxx_messageInfo_Handler.DiscardUnknown(m)
}

var xxx_messageInfo_Handler proto.InternalMessageInfo

func (m *Handler) GetSpecs() []*Spec {
	if m != nil {
		return m.Specs
	}
	return nil
}

// A Registration contains all the information the system needs to register a plugin.
// This message type includes all of the fields you get by calling Identity on a plugins.Plugin instance,
// which together uniquely identifies a plugin at a particular version.
type Registration struct {
	// Name is the plugin's name, without any version information in it.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// ID is the plugin's unique identifier (within a plugins repository).
	Id string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	// Ver is the plugin's version.
	Ver *version.Version `protobuf:"bytes,4,opt,name=ver,proto3" json:"ver,omitempty"`
	// Specs contains the specifications within which the plugin works.
	Specs []*Spec `protobuf:"bytes,5,rep,name=specs,proto3" json:"specs,omitempty"`
	// Hooks is all of the hooks which the plugin wants to handle with its hook handlers.
	Hooks map[string]*Handler `protobuf:"bytes,6,rep,name=hooks,proto3" json:"hooks,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// Filters is all of the filters which the plugin wants to handle with its filter handlers.
	Filters map[string]*Handler `protobuf:"bytes,7,rep,name=filters,proto3" json:"filters,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// CustomHooks contains all of a plugin's custom defined hooks.
	CustomHooks []string `protobuf:"bytes,8,rep,name=custom_hooks,json=customHooks,proto3" json:"custom_hooks,omitempty"`
	// CustomFilters contains all of a plugin's custom defined filters.
	CustomFilters        []string `protobuf:"bytes,9,rep,name=custom_filters,json=customFilters,proto3" json:"custom_filters,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Registration) Reset()         { *m = Registration{} }
func (m *Registration) String() string { return proto.CompactTextString(m) }
func (*Registration) ProtoMessage()    {}
func (*Registration) Descriptor() ([]byte, []int) {
	return fileDescriptor_internal_abdee2133d4c549b, []int{2}
}
func (m *Registration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Registration.Unmarshal(m, b)
}
func (m *Registration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Registration.Marshal(b, m, deterministic)
}
func (dst *Registration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Registration.Merge(dst, src)
}
func (m *Registration) XXX_Size() int {
	return xxx_messageInfo_Registration.Size(m)
}
func (m *Registration) XXX_DiscardUnknown() {
	xxx_messageInfo_Registration.DiscardUnknown(m)
}

var xxx_messageInfo_Registration proto.InternalMessageInfo

func (m *Registration) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Registration) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Registration) GetVer() *version.Version {
	if m != nil {
		return m.Ver
	}
	return nil
}

func (m *Registration) GetSpecs() []*Spec {
	if m != nil {
		return m.Specs
	}
	return nil
}

func (m *Registration) GetHooks() map[string]*Handler {
	if m != nil {
		return m.Hooks
	}
	return nil
}

func (m *Registration) GetFilters() map[string]*Handler {
	if m != nil {
		return m.Filters
	}
	return nil
}

func (m *Registration) GetCustomHooks() []string {
	if m != nil {
		return m.CustomHooks
	}
	return nil
}

func (m *Registration) GetCustomFilters() []string {
	if m != nil {
		return m.CustomFilters
	}
	return nil
}

type InitRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InitRequest) Reset()         { *m = InitRequest{} }
func (m *InitRequest) String() string { return proto.CompactTextString(m) }
func (*InitRequest) ProtoMessage()    {}
func (*InitRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_internal_abdee2133d4c549b, []int{3}
}
func (m *InitRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitRequest.Unmarshal(m, b)
}
func (m *InitRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitRequest.Marshal(b, m, deterministic)
}
func (dst *InitRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitRequest.Merge(dst, src)
}
func (m *InitRequest) XXX_Size() int {
	return xxx_messageInfo_InitRequest.Size(m)
}
func (m *InitRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InitRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InitRequest proto.InternalMessageInfo

type HookRequest struct {
	HookName             string   `protobuf:"bytes,1,opt,name=hook_name,json=hookName,proto3" json:"hook_name,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HookRequest) Reset()         { *m = HookRequest{} }
func (m *HookRequest) String() string { return proto.CompactTextString(m) }
func (*HookRequest) ProtoMessage()    {}
func (*HookRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_internal_abdee2133d4c549b, []int{4}
}
func (m *HookRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HookRequest.Unmarshal(m, b)
}
func (m *HookRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HookRequest.Marshal(b, m, deterministic)
}
func (dst *HookRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HookRequest.Merge(dst, src)
}
func (m *HookRequest) XXX_Size() int {
	return xxx_messageInfo_HookRequest.Size(m)
}
func (m *HookRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HookRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HookRequest proto.InternalMessageInfo

func (m *HookRequest) GetHookName() string {
	if m != nil {
		return m.HookName
	}
	return ""
}

func (m *HookRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type HookResponse struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HookResponse) Reset()         { *m = HookResponse{} }
func (m *HookResponse) String() string { return proto.CompactTextString(m) }
func (*HookResponse) ProtoMessage()    {}
func (*HookResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_internal_abdee2133d4c549b, []int{5}
}
func (m *HookResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HookResponse.Unmarshal(m, b)
}
func (m *HookResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HookResponse.Marshal(b, m, deterministic)
}
func (dst *HookResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HookResponse.Merge(dst, src)
}
func (m *HookResponse) XXX_Size() int {
	return xxx_messageInfo_HookResponse.Size(m)
}
func (m *HookResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HookResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HookResponse proto.InternalMessageInfo

func (m *HookResponse) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type FilterData struct {
	FilterName           string   `protobuf:"bytes,1,opt,name=filter_name,json=filterName,proto3" json:"filter_name,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FilterData) Reset()         { *m = FilterData{} }
func (m *FilterData) String() string { return proto.CompactTextString(m) }
func (*FilterData) ProtoMessage()    {}
func (*FilterData) Descriptor() ([]byte, []int) {
	return fileDescriptor_internal_abdee2133d4c549b, []int{6}
}
func (m *FilterData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FilterData.Unmarshal(m, b)
}
func (m *FilterData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FilterData.Marshal(b, m, deterministic)
}
func (dst *FilterData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FilterData.Merge(dst, src)
}
func (m *FilterData) XXX_Size() int {
	return xxx_messageInfo_FilterData.Size(m)
}
func (m *FilterData) XXX_DiscardUnknown() {
	xxx_messageInfo_FilterData.DiscardUnknown(m)
}

var xxx_messageInfo_FilterData proto.InternalMessageInfo

func (m *FilterData) GetFilterName() string {
	if m != nil {
		return m.FilterName
	}
	return ""
}

func (m *FilterData) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type FullRegistration struct {
	Reg                  *Registration `protobuf:"bytes,1,opt,name=reg,proto3" json:"reg,omitempty"`
	Repo                 *Repository   `protobuf:"bytes,2,opt,name=repo,proto3" json:"repo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *FullRegistration) Reset()         { *m = FullRegistration{} }
func (m *FullRegistration) String() string { return proto.CompactTextString(m) }
func (*FullRegistration) ProtoMessage()    {}
func (*FullRegistration) Descriptor() ([]byte, []int) {
	return fileDescriptor_internal_abdee2133d4c549b, []int{7}
}
func (m *FullRegistration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FullRegistration.Unmarshal(m, b)
}
func (m *FullRegistration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FullRegistration.Marshal(b, m, deterministic)
}
func (dst *FullRegistration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FullRegistration.Merge(dst, src)
}
func (m *FullRegistration) XXX_Size() int {
	return xxx_messageInfo_FullRegistration.Size(m)
}
func (m *FullRegistration) XXX_DiscardUnknown() {
	xxx_messageInfo_FullRegistration.DiscardUnknown(m)
}

var xxx_messageInfo_FullRegistration proto.InternalMessageInfo

func (m *FullRegistration) GetReg() *Registration {
	if m != nil {
		return m.Reg
	}
	return nil
}

func (m *FullRegistration) GetRepo() *Repository {
	if m != nil {
		return m.Repo
	}
	return nil
}

type Repository struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	RootUrl              string   `protobuf:"bytes,3,opt,name=root_url,json=rootUrl,proto3" json:"root_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Repository) Reset()         { *m = Repository{} }
func (m *Repository) String() string { return proto.CompactTextString(m) }
func (*Repository) ProtoMessage()    {}
func (*Repository) Descriptor() ([]byte, []int) {
	return fileDescriptor_internal_abdee2133d4c549b, []int{8}
}
func (m *Repository) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Repository.Unmarshal(m, b)
}
func (m *Repository) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Repository.Marshal(b, m, deterministic)
}
func (dst *Repository) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Repository.Merge(dst, src)
}
func (m *Repository) XXX_Size() int {
	return xxx_messageInfo_Repository.Size(m)
}
func (m *Repository) XXX_DiscardUnknown() {
	xxx_messageInfo_Repository.DiscardUnknown(m)
}

var xxx_messageInfo_Repository proto.InternalMessageInfo

func (m *Repository) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Repository) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Repository) GetRootUrl() string {
	if m != nil {
		return m.RootUrl
	}
	return ""
}

func init() {
	proto.RegisterType((*Spec)(nil), "internal.Spec")
	proto.RegisterType((*Handler)(nil), "internal.Handler")
	proto.RegisterType((*Registration)(nil), "internal.Registration")
	proto.RegisterMapType((map[string]*Handler)(nil), "internal.Registration.FiltersEntry")
	proto.RegisterMapType((map[string]*Handler)(nil), "internal.Registration.HooksEntry")
	proto.RegisterType((*InitRequest)(nil), "internal.InitRequest")
	proto.RegisterType((*HookRequest)(nil), "internal.HookRequest")
	proto.RegisterType((*HookResponse)(nil), "internal.HookResponse")
	proto.RegisterType((*FilterData)(nil), "internal.FilterData")
	proto.RegisterType((*FullRegistration)(nil), "internal.FullRegistration")
	proto.RegisterType((*Repository)(nil), "internal.Repository")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PluginClient is the client API for Plugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PluginClient interface {
	Init(ctx context.Context, in *InitRequest, opts ...grpc.CallOption) (*Registration, error)
	DoHook(ctx context.Context, in *HookRequest, opts ...grpc.CallOption) (*HookResponse, error)
	DoFilter(ctx context.Context, in *FilterData, opts ...grpc.CallOption) (*FilterData, error)
}

type pluginClient struct {
	cc *grpc.ClientConn
}

func NewPluginClient(cc *grpc.ClientConn) PluginClient {
	return &pluginClient{cc}
}

func (c *pluginClient) Init(ctx context.Context, in *InitRequest, opts ...grpc.CallOption) (*Registration, error) {
	out := new(Registration)
	err := c.cc.Invoke(ctx, "/internal.Plugin/Init", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginClient) DoHook(ctx context.Context, in *HookRequest, opts ...grpc.CallOption) (*HookResponse, error) {
	out := new(HookResponse)
	err := c.cc.Invoke(ctx, "/internal.Plugin/DoHook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginClient) DoFilter(ctx context.Context, in *FilterData, opts ...grpc.CallOption) (*FilterData, error) {
	out := new(FilterData)
	err := c.cc.Invoke(ctx, "/internal.Plugin/DoFilter", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PluginServer is the server API for Plugin service.
type PluginServer interface {
	Init(context.Context, *InitRequest) (*Registration, error)
	DoHook(context.Context, *HookRequest) (*HookResponse, error)
	DoFilter(context.Context, *FilterData) (*FilterData, error)
}

func RegisterPluginServer(s *grpc.Server, srv PluginServer) {
	s.RegisterService(&_Plugin_serviceDesc, srv)
}

func _Plugin_Init_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServer).Init(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/internal.Plugin/Init",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServer).Init(ctx, req.(*InitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plugin_DoHook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServer).DoHook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/internal.Plugin/DoHook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServer).DoHook(ctx, req.(*HookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plugin_DoFilter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FilterData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServer).DoFilter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/internal.Plugin/DoFilter",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServer).DoFilter(ctx, req.(*FilterData))
	}
	return interceptor(ctx, in, info, handler)
}

var _Plugin_serviceDesc = grpc.ServiceDesc{
	ServiceName: "internal.Plugin",
	HandlerType: (*PluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Init",
			Handler:    _Plugin_Init_Handler,
		},
		{
			MethodName: "DoHook",
			Handler:    _Plugin_DoHook_Handler,
		},
		{
			MethodName: "DoFilter",
			Handler:    _Plugin_DoFilter_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "plugins/internal/internal.proto",
}

func init() {
	proto.RegisterFile("plugins/internal/internal.proto", fileDescriptor_internal_abdee2133d4c549b)
}

var fileDescriptor_internal_abdee2133d4c549b = []byte{
	// 575 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0x5d, 0x6f, 0xd3, 0x30,
	0x14, 0x55, 0x9a, 0xf4, 0xeb, 0xa6, 0xad, 0x8a, 0x35, 0x50, 0xe8, 0x1e, 0xd6, 0x05, 0x10, 0x79,
	0x6a, 0xa0, 0x08, 0x86, 0x90, 0x40, 0x02, 0x95, 0x69, 0x68, 0x02, 0x21, 0x23, 0x78, 0xe0, 0xa5,
	0xca, 0x5a, 0xaf, 0xb5, 0x9a, 0xc6, 0xc1, 0x76, 0x8a, 0xca, 0xaf, 0xe2, 0xf7, 0xf0, 0x6b, 0x90,
	0xed, 0x74, 0xf1, 0xd0, 0x8a, 0x90, 0x78, 0xca, 0xbd, 0x37, 0xe7, 0xde, 0x73, 0x7c, 0x4f, 0x62,
	0x38, 0xca, 0xd3, 0x62, 0x41, 0x33, 0x11, 0xd3, 0x4c, 0x12, 0x9e, 0x25, 0xe9, 0x55, 0x30, 0xca,
	0x39, 0x93, 0x0c, 0xb5, 0x76, 0xf9, 0xe0, 0x50, 0x6e, 0x73, 0x22, 0xe2, 0x0d, 0xe1, 0x82, 0xb2,
	0x6c, 0xf7, 0x34, 0xb0, 0xf0, 0x11, 0x78, 0x9f, 0x72, 0x32, 0x43, 0x08, 0x3c, 0x05, 0x0b, 0x9c,
	0xa1, 0x13, 0x75, 0xb1, 0x8e, 0xd1, 0x01, 0xd4, 0x37, 0x49, 0x5a, 0x90, 0xa0, 0x36, 0x74, 0xa2,
	0x36, 0x36, 0x49, 0x18, 0x43, 0xf3, 0x2c, 0xc9, 0xe6, 0x29, 0xe1, 0xe8, 0x3e, 0xd4, 0x45, 0x4e,
	0x66, 0x22, 0x70, 0x86, 0x6e, 0xe4, 0x8f, 0x7b, 0xa3, 0x2b, 0x0d, 0x6a, 0x26, 0x36, 0x2f, 0xc3,
	0x5f, 0x2e, 0x74, 0x30, 0x59, 0x50, 0x21, 0x79, 0x22, 0x29, 0xcb, 0x14, 0x57, 0x96, 0xac, 0x0d,
	0x57, 0x1b, 0xeb, 0x18, 0xf5, 0xa0, 0x46, 0xe7, 0x25, 0x51, 0x8d, 0xce, 0x51, 0x08, 0xee, 0x86,
	0xf0, 0xc0, 0x1b, 0x3a, 0x91, 0x3f, 0xee, 0x8f, 0x76, 0xa2, 0xbf, 0x98, 0x27, 0x56, 0x2f, 0x2b,
	0xfa, 0xfa, 0x5f, 0xe8, 0xd1, 0x09, 0xd4, 0x97, 0x8c, 0xad, 0x44, 0xd0, 0xd0, 0xa8, 0xe3, 0x0a,
	0x65, 0x8b, 0x1a, 0x9d, 0x29, 0xcc, 0xdb, 0x4c, 0xf2, 0x2d, 0x36, 0x78, 0xf4, 0x12, 0x9a, 0x97,
	0x34, 0x95, 0x84, 0x8b, 0xa0, 0xa9, 0x5b, 0xef, 0xed, 0x69, 0x3d, 0x35, 0x28, 0xd3, 0xbc, 0xeb,
	0x41, 0xc7, 0xd0, 0x99, 0x15, 0x42, 0xb2, 0xf5, 0xd4, 0xd0, 0xb7, 0x86, 0x6e, 0xd4, 0xc6, 0xbe,
	0xa9, 0x69, 0x36, 0xf4, 0x00, 0x7a, 0x25, 0x64, 0x47, 0xd4, 0xd6, 0xa0, 0xae, 0xa9, 0x96, 0x73,
	0x07, 0xe7, 0x00, 0x95, 0x3a, 0xd4, 0x07, 0x77, 0x45, 0xb6, 0xe5, 0xf2, 0x54, 0x88, 0x1e, 0xda,
	0x3e, 0xf9, 0xe3, 0x5b, 0x95, 0xcc, 0xd2, 0xa8, 0xd2, 0xba, 0x17, 0xb5, 0xe7, 0xce, 0xe0, 0x3d,
	0x74, 0x6c, 0xbd, 0xff, 0x39, 0x2e, 0xec, 0x82, 0xff, 0x2e, 0xa3, 0x12, 0x93, 0x6f, 0x05, 0x11,
	0x32, 0x7c, 0x05, 0xbe, 0x92, 0x5a, 0xa6, 0xe8, 0x10, 0xda, 0xea, 0xf0, 0x53, 0xcb, 0xee, 0x96,
	0x2a, 0x7c, 0x50, 0x96, 0x23, 0xf0, 0xe6, 0x89, 0x4c, 0x34, 0x4d, 0x07, 0xeb, 0x38, 0x0c, 0xa1,
	0x63, 0xfa, 0x45, 0xce, 0x32, 0x51, 0x61, 0x1c, 0x0b, 0xf3, 0x1a, 0xc0, 0x9c, 0x60, 0x92, 0xc8,
	0x04, 0x1d, 0x81, 0x6f, 0x96, 0x67, 0x93, 0x80, 0x29, 0xed, 0xa5, 0xb9, 0x84, 0xfe, 0x69, 0x91,
	0xa6, 0xd7, 0xbe, 0xca, 0x08, 0x5c, 0x4e, 0x16, 0x7a, 0x80, 0x3f, 0xbe, 0x73, 0xb3, 0xd5, 0x58,
	0x41, 0x50, 0x04, 0x1e, 0x27, 0x39, 0x2b, 0xf7, 0x73, 0x60, 0x43, 0x73, 0x26, 0xa8, 0x64, 0x7c,
	0x8b, 0x35, 0x22, 0x3c, 0x07, 0xa8, 0x6a, 0xff, 0xf4, 0xdd, 0xdf, 0x85, 0x16, 0x67, 0x4c, 0x4e,
	0x0b, 0x9e, 0x06, 0xae, 0xae, 0x36, 0x55, 0xfe, 0x99, 0xa7, 0xe3, 0x9f, 0x0e, 0x34, 0x3e, 0xea,
	0xbf, 0x1e, 0x3d, 0x05, 0x4f, 0x6d, 0x1d, 0xdd, 0xae, 0xb8, 0x2d, 0x17, 0x06, 0x7b, 0xd4, 0xa3,
	0x13, 0x68, 0x4c, 0x98, 0xda, 0xaf, 0xdd, 0x68, 0xf9, 0x65, 0x37, 0x5e, 0xb3, 0xe1, 0x19, 0xb4,
	0x26, 0xcc, 0x2c, 0x1d, 0x59, 0xe7, 0xad, 0x6c, 0x18, 0xdc, 0x58, 0x7d, 0xf3, 0xf8, 0x6b, 0xbc,
	0xa0, 0x72, 0x59, 0x5c, 0x8c, 0x66, 0x6c, 0x1d, 0xcf, 0x67, 0x4b, 0x92, 0xad, 0xe2, 0x75, 0xf2,
	0x83, 0x7c, 0xa7, 0x9c, 0xc4, 0xf9, 0x6a, 0x11, 0xff, 0x79, 0x8d, 0x5d, 0x34, 0xf4, 0xbd, 0xf4,
	0xe4, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc8, 0x2b, 0x6c, 0xe0, 0xe1, 0x04, 0x00, 0x00,
}
