// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/user/user.proto

package user

import (
	fmt "fmt"
	_ "github.com/dchenk/mazewire/pkg/types/time"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// A NewUser contains the information needed to create a new user.
type NewUser struct {
	// Username.
	Uname string `protobuf:"bytes,2,opt,name=uname,proto3" json:"uname,omitempty"`
	// Email address.
	Email string `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	// The user's chosen password in plain text.
	Pass string `protobuf:"bytes,4,opt,name=pass,proto3" json:"pass,omitempty"`
	// First name.
	Fname string `protobuf:"bytes,5,opt,name=fname,proto3" json:"fname,omitempty"`
	// Last name.
	Lname string `protobuf:"bytes,6,opt,name=lname,proto3" json:"lname,omitempty"`
	// The user's role in the site being accessed in the current request.
	Role                 string   `protobuf:"bytes,7,opt,name=role,proto3" json:"role,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewUser) Reset()         { *m = NewUser{} }
func (m *NewUser) String() string { return proto.CompactTextString(m) }
func (*NewUser) ProtoMessage()    {}
func (*NewUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_3bc452c1a8bd0aa8, []int{0}
}

func (m *NewUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewUser.Unmarshal(m, b)
}
func (m *NewUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewUser.Marshal(b, m, deterministic)
}
func (m *NewUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewUser.Merge(m, src)
}
func (m *NewUser) XXX_Size() int {
	return xxx_messageInfo_NewUser.Size(m)
}
func (m *NewUser) XXX_DiscardUnknown() {
	xxx_messageInfo_NewUser.DiscardUnknown(m)
}

var xxx_messageInfo_NewUser proto.InternalMessageInfo

func (m *NewUser) GetUname() string {
	if m != nil {
		return m.Uname
	}
	return ""
}

func (m *NewUser) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *NewUser) GetPass() string {
	if m != nil {
		return m.Pass
	}
	return ""
}

func (m *NewUser) GetFname() string {
	if m != nil {
		return m.Fname
	}
	return ""
}

func (m *NewUser) GetLname() string {
	if m != nil {
		return m.Lname
	}
	return ""
}

func (m *NewUser) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func init() {
	proto.RegisterType((*NewUser)(nil), "user.NewUser")
}

func init() { proto.RegisterFile("api/user/user.proto", fileDescriptor_3bc452c1a8bd0aa8) }

var fileDescriptor_3bc452c1a8bd0aa8 = []byte{
	// 190 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4e, 0x2c, 0xc8, 0xd4,
	0x2f, 0x2d, 0x4e, 0x2d, 0x02, 0x13, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0x2c, 0x20, 0xb6,
	0x94, 0x68, 0x49, 0x65, 0x41, 0x6a, 0xb1, 0x7e, 0x49, 0x66, 0x6e, 0x2a, 0x98, 0x80, 0x48, 0x2a,
	0x75, 0x32, 0x72, 0xb1, 0xfb, 0xa5, 0x96, 0x87, 0x16, 0xa7, 0x16, 0x09, 0x89, 0x70, 0xb1, 0x96,
	0xe6, 0x25, 0xe6, 0xa6, 0x4a, 0x30, 0x29, 0x30, 0x6a, 0x70, 0x06, 0x41, 0x38, 0x20, 0xd1, 0xd4,
	0xdc, 0xc4, 0xcc, 0x1c, 0x09, 0x66, 0x88, 0x28, 0x98, 0x23, 0x24, 0xc4, 0xc5, 0x52, 0x90, 0x58,
	0x5c, 0x2c, 0xc1, 0x02, 0x16, 0x04, 0xb3, 0x41, 0x2a, 0xd3, 0xc0, 0xfa, 0x59, 0x21, 0x2a, 0xd3,
	0x60, 0xfa, 0x73, 0xc0, 0xa2, 0x6c, 0x10, 0x51, 0x30, 0x07, 0xa4, 0xbf, 0x28, 0x3f, 0x27, 0x55,
	0x82, 0x1d, 0xa2, 0x1f, 0xc4, 0x76, 0xd2, 0x8c, 0x52, 0x4f, 0xcf, 0x2c, 0xc9, 0x28, 0x4d, 0xd2,
	0x4b, 0xce, 0xcf, 0xd5, 0x4f, 0x49, 0xce, 0x48, 0xcd, 0xcb, 0xd6, 0xcf, 0x4d, 0xac, 0x4a, 0x2d,
	0xcf, 0x2c, 0x4a, 0xd5, 0x2f, 0xc8, 0x4e, 0xd7, 0x87, 0x79, 0x2f, 0x89, 0x0d, 0xec, 0x7a, 0x63,
	0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xe6, 0xd5, 0x82, 0xc2, 0xf1, 0x00, 0x00, 0x00,
}
