// Code generated by protoc-gen-go. DO NOT EDIT.
// source: data/tables.proto

package data // import "github.com/dchenk/mazewire/pkg/data"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import time "github.com/dchenk/mazewire/pkg/types/time"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// A Site is the basic settings of a site, except for the time when the site was created.
// Everything else that shapes a site is in either an Option or a Blob.
type Site struct {
	// Row ID in the table.
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// The domain (no slashes; possibly includes sub-domain).
	Domain string `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`
	// The name of the website.
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// The URL of the main logo file.
	Logo string `protobuf:"bytes,4,opt,name=logo,proto3" json:"logo,omitempty"`
	// The URL of the favicon file.
	Favicon string `protobuf:"bytes,5,opt,name=favicon,proto3" json:"favicon,omitempty"`
	// The status of the TLS on the domain: 0 = none, 1 = configuring, 2 = good
	Tls                  uint32   `protobuf:"varint,6,opt,name=tls,proto3" json:"tls,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Site) Reset()         { *m = Site{} }
func (m *Site) String() string { return proto.CompactTextString(m) }
func (*Site) ProtoMessage()    {}
func (*Site) Descriptor() ([]byte, []int) {
	return fileDescriptor_tables_e838647ad188493e, []int{0}
}
func (m *Site) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Site.Unmarshal(m, b)
}
func (m *Site) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Site.Marshal(b, m, deterministic)
}
func (dst *Site) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Site.Merge(dst, src)
}
func (m *Site) XXX_Size() int {
	return xxx_messageInfo_Site.Size(m)
}
func (m *Site) XXX_DiscardUnknown() {
	xxx_messageInfo_Site.DiscardUnknown(m)
}

var xxx_messageInfo_Site proto.InternalMessageInfo

func (m *Site) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Site) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

func (m *Site) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Site) GetLogo() string {
	if m != nil {
		return m.Logo
	}
	return ""
}

func (m *Site) GetFavicon() string {
	if m != nil {
		return m.Favicon
	}
	return ""
}

func (m *Site) GetTls() uint32 {
	if m != nil {
		return m.Tls
	}
	return 0
}

// A Blob is a general-use container for binary data.
type Blob struct {
	// Row ID in the table.
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// General field to specify what kind of blob this is.
	Role string `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	// Key to connect the Blob with content (not an actual foreign key).
	K int64 `protobuf:"varint,3,opt,name=k,proto3" json:"k,omitempty"`
	// The data.
	V []byte `protobuf:"bytes,4,opt,name=v,proto3" json:"v,omitempty"`
	// Time of the last update.
	Updated              *time.Time `protobuf:"bytes,5,opt,name=updated,proto3" json:"updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Blob) Reset()         { *m = Blob{} }
func (m *Blob) String() string { return proto.CompactTextString(m) }
func (*Blob) ProtoMessage()    {}
func (*Blob) Descriptor() ([]byte, []int) {
	return fileDescriptor_tables_e838647ad188493e, []int{1}
}
func (m *Blob) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Blob.Unmarshal(m, b)
}
func (m *Blob) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Blob.Marshal(b, m, deterministic)
}
func (dst *Blob) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Blob.Merge(dst, src)
}
func (m *Blob) XXX_Size() int {
	return xxx_messageInfo_Blob.Size(m)
}
func (m *Blob) XXX_DiscardUnknown() {
	xxx_messageInfo_Blob.DiscardUnknown(m)
}

var xxx_messageInfo_Blob proto.InternalMessageInfo

func (m *Blob) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Blob) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func (m *Blob) GetK() int64 {
	if m != nil {
		return m.K
	}
	return 0
}

func (m *Blob) GetV() []byte {
	if m != nil {
		return m.V
	}
	return nil
}

func (m *Blob) GetUpdated() *time.Time {
	if m != nil {
		return m.Updated
	}
	return nil
}

// A Content is piece of the content of an email body. Each email must have at least one Content.
type Content struct {
	// Row ID in the table.
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Site ID that the content is part of.
	Site int64 `protobuf:"varint,2,opt,name=site,proto3" json:"site,omitempty"`
	// Valid URL path part with no slashes.
	Slug string `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	// The ID of the author.
	Author int64 `protobuf:"varint,4,opt,name=author,proto3" json:"author,omitempty"`
	// The general type of the content, such as "page" or "post".
	Type string `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	// Either 0 or the ID of the parent in the same table.
	Parent int64 `protobuf:"varint,6,opt,name=parent,proto3" json:"parent,omitempty"`
	// Title for displaying.
	Title string `protobuf:"bytes,7,opt,name=title,proto3" json:"title,omitempty"`
	// Title to give in an HTML meta tag; optional but not null.
	MetaTitle string `protobuf:"bytes,8,opt,name=meta_title,json=metaTitle,proto3" json:"meta_title,omitempty"`
	// Description to give in an HTML meta tag; optional but not null.
	MetaDesc string `protobuf:"bytes,9,opt,name=meta_desc,json=metaDesc,proto3" json:"meta_desc,omitempty"`
	// Either blank or the published (and compiled) body, cached for quick loading.
	Body []byte `protobuf:"bytes,10,opt,name=body,proto3" json:"body,omitempty"`
	// Publication status is one of 'draft', 'published', 'unsaved', or 'trashed';
	// defaults to 'draft' in the database.
	Status string `protobuf:"bytes,11,opt,name=status,proto3" json:"status,omitempty"`
	// Time of the last update.
	Updated              *time.Time `protobuf:"bytes,12,opt,name=updated,proto3" json:"updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Content) Reset()         { *m = Content{} }
func (m *Content) String() string { return proto.CompactTextString(m) }
func (*Content) ProtoMessage()    {}
func (*Content) Descriptor() ([]byte, []int) {
	return fileDescriptor_tables_e838647ad188493e, []int{2}
}
func (m *Content) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Content.Unmarshal(m, b)
}
func (m *Content) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Content.Marshal(b, m, deterministic)
}
func (dst *Content) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Content.Merge(dst, src)
}
func (m *Content) XXX_Size() int {
	return xxx_messageInfo_Content.Size(m)
}
func (m *Content) XXX_DiscardUnknown() {
	xxx_messageInfo_Content.DiscardUnknown(m)
}

var xxx_messageInfo_Content proto.InternalMessageInfo

func (m *Content) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Content) GetSite() int64 {
	if m != nil {
		return m.Site
	}
	return 0
}

func (m *Content) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

func (m *Content) GetAuthor() int64 {
	if m != nil {
		return m.Author
	}
	return 0
}

func (m *Content) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Content) GetParent() int64 {
	if m != nil {
		return m.Parent
	}
	return 0
}

func (m *Content) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Content) GetMetaTitle() string {
	if m != nil {
		return m.MetaTitle
	}
	return ""
}

func (m *Content) GetMetaDesc() string {
	if m != nil {
		return m.MetaDesc
	}
	return ""
}

func (m *Content) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *Content) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Content) GetUpdated() *time.Time {
	if m != nil {
		return m.Updated
	}
	return nil
}

// A User contains all the basic info of registered a user.
type User struct {
	// Row ID in the table.
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Username.
	Uname string `protobuf:"bytes,2,opt,name=uname,proto3" json:"uname,omitempty"`
	// Email address.
	Email string `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	// Password, already hashed.
	Pass []byte `protobuf:"bytes,4,opt,name=pass,proto3" json:"pass,omitempty"`
	// First name.
	Fname string `protobuf:"bytes,5,opt,name=fname,proto3" json:"fname,omitempty"`
	// Last name.
	Lname string `protobuf:"bytes,6,opt,name=lname,proto3" json:"lname,omitempty"`
	// The user's role in the site being accessed in the current request.
	Role string `protobuf:"bytes,7,opt,name=role,proto3" json:"role,omitempty"`
	// Time of the last update.
	Updated              *time.Time `protobuf:"bytes,8,opt,name=updated,proto3" json:"updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_tables_e838647ad188493e, []int{3}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (dst *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(dst, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetUname() string {
	if m != nil {
		return m.Uname
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetPass() []byte {
	if m != nil {
		return m.Pass
	}
	return nil
}

func (m *User) GetFname() string {
	if m != nil {
		return m.Fname
	}
	return ""
}

func (m *User) GetLname() string {
	if m != nil {
		return m.Lname
	}
	return ""
}

func (m *User) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func (m *User) GetUpdated() *time.Time {
	if m != nil {
		return m.Updated
	}
	return nil
}

// A UserMeta struct contains the key and value of a meta datum for a user (along with the timestamp of the
// last update of the row). The rows in the database table are primary-keyed by both the user ID and the K.
type UserMeta struct {
	// UserId is a foreign key to a User ID.
	UserId int64  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	K      string `protobuf:"bytes,2,opt,name=k,proto3" json:"k,omitempty"`
	V      []byte `protobuf:"bytes,3,opt,name=v,proto3" json:"v,omitempty"`
	// Time of the last update.
	Updated              *time.Time `protobuf:"bytes,4,opt,name=updated,proto3" json:"updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *UserMeta) Reset()         { *m = UserMeta{} }
func (m *UserMeta) String() string { return proto.CompactTextString(m) }
func (*UserMeta) ProtoMessage()    {}
func (*UserMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_tables_e838647ad188493e, []int{4}
}
func (m *UserMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserMeta.Unmarshal(m, b)
}
func (m *UserMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserMeta.Marshal(b, m, deterministic)
}
func (dst *UserMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserMeta.Merge(dst, src)
}
func (m *UserMeta) XXX_Size() int {
	return xxx_messageInfo_UserMeta.Size(m)
}
func (m *UserMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_UserMeta.DiscardUnknown(m)
}

var xxx_messageInfo_UserMeta proto.InternalMessageInfo

func (m *UserMeta) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *UserMeta) GetK() string {
	if m != nil {
		return m.K
	}
	return ""
}

func (m *UserMeta) GetV() []byte {
	if m != nil {
		return m.V
	}
	return nil
}

func (m *UserMeta) GetUpdated() *time.Time {
	if m != nil {
		return m.Updated
	}
	return nil
}

// An Option is a key => value pair holding a small amount of data for a site, the primary key being the
// composite of the site ID and the value of K.
type Option struct {
	// Site is a foreign key to a Site ID.
	Site                 int64    `protobuf:"varint,1,opt,name=site,proto3" json:"site,omitempty"`
	K                    string   `protobuf:"bytes,2,opt,name=k,proto3" json:"k,omitempty"`
	V                    []byte   `protobuf:"bytes,3,opt,name=v,proto3" json:"v,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Option) Reset()         { *m = Option{} }
func (m *Option) String() string { return proto.CompactTextString(m) }
func (*Option) ProtoMessage()    {}
func (*Option) Descriptor() ([]byte, []int) {
	return fileDescriptor_tables_e838647ad188493e, []int{5}
}
func (m *Option) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Option.Unmarshal(m, b)
}
func (m *Option) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Option.Marshal(b, m, deterministic)
}
func (dst *Option) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Option.Merge(dst, src)
}
func (m *Option) XXX_Size() int {
	return xxx_messageInfo_Option.Size(m)
}
func (m *Option) XXX_DiscardUnknown() {
	xxx_messageInfo_Option.DiscardUnknown(m)
}

var xxx_messageInfo_Option proto.InternalMessageInfo

func (m *Option) GetSite() int64 {
	if m != nil {
		return m.Site
	}
	return 0
}

func (m *Option) GetK() string {
	if m != nil {
		return m.K
	}
	return ""
}

func (m *Option) GetV() []byte {
	if m != nil {
		return m.V
	}
	return nil
}

// A Media represents a static media item belonging to a website.
//
// The fields Id, Ext, Site, and Name are required; the other strings default to empty strings and must not
// be null; the Uploaded time defaults to the current time in the database.
type Media struct {
	// A UUID encoded in base32 without padding.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// File extension, starting with a dot if set; optional but not null.
	Ext string `protobuf:"bytes,2,opt,name=ext,proto3" json:"ext,omitempty"`
	// Foreign key to a Site ID.
	Site int64 `protobuf:"varint,3,opt,name=site,proto3" json:"site,omitempty"`
	// A user-given name.
	Name string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	// HTML "alt" tag.
	Alt string `protobuf:"bytes,5,opt,name=alt,proto3" json:"alt,omitempty"`
	// A description.
	Desc string `protobuf:"bytes,6,opt,name=desc,proto3" json:"desc,omitempty"`
	// Time when the object was uploaded.
	Uploaded             *time.Time `protobuf:"bytes,7,opt,name=uploaded,proto3" json:"uploaded,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Media) Reset()         { *m = Media{} }
func (m *Media) String() string { return proto.CompactTextString(m) }
func (*Media) ProtoMessage()    {}
func (*Media) Descriptor() ([]byte, []int) {
	return fileDescriptor_tables_e838647ad188493e, []int{6}
}
func (m *Media) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Media.Unmarshal(m, b)
}
func (m *Media) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Media.Marshal(b, m, deterministic)
}
func (dst *Media) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Media.Merge(dst, src)
}
func (m *Media) XXX_Size() int {
	return xxx_messageInfo_Media.Size(m)
}
func (m *Media) XXX_DiscardUnknown() {
	xxx_messageInfo_Media.DiscardUnknown(m)
}

var xxx_messageInfo_Media proto.InternalMessageInfo

func (m *Media) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Media) GetExt() string {
	if m != nil {
		return m.Ext
	}
	return ""
}

func (m *Media) GetSite() int64 {
	if m != nil {
		return m.Site
	}
	return 0
}

func (m *Media) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Media) GetAlt() string {
	if m != nil {
		return m.Alt
	}
	return ""
}

func (m *Media) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *Media) GetUploaded() *time.Time {
	if m != nil {
		return m.Uploaded
	}
	return nil
}

// A SiteMessage is a notification message for a site, to be shown to all users whose role on the
// site is at least Role.
type SiteMessage struct {
	// Row ID in the table.
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// SiteId is a foreign key to a Site ID.
	SiteId int64 `protobuf:"varint,2,opt,name=site_id,json=siteId,proto3" json:"site_id,omitempty"`
	// Role is the mimum role a user must have to be shown the message.
	Role string `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	// K is a key to identify the message.
	K       string `protobuf:"bytes,4,opt,name=k,proto3" json:"k,omitempty"`
	Message string `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	// Time when the message was created.
	Created              *time.Time `protobuf:"bytes,6,opt,name=created,proto3" json:"created,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *SiteMessage) Reset()         { *m = SiteMessage{} }
func (m *SiteMessage) String() string { return proto.CompactTextString(m) }
func (*SiteMessage) ProtoMessage()    {}
func (*SiteMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_tables_e838647ad188493e, []int{7}
}
func (m *SiteMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SiteMessage.Unmarshal(m, b)
}
func (m *SiteMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SiteMessage.Marshal(b, m, deterministic)
}
func (dst *SiteMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SiteMessage.Merge(dst, src)
}
func (m *SiteMessage) XXX_Size() int {
	return xxx_messageInfo_SiteMessage.Size(m)
}
func (m *SiteMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_SiteMessage.DiscardUnknown(m)
}

var xxx_messageInfo_SiteMessage proto.InternalMessageInfo

func (m *SiteMessage) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SiteMessage) GetSiteId() int64 {
	if m != nil {
		return m.SiteId
	}
	return 0
}

func (m *SiteMessage) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func (m *SiteMessage) GetK() string {
	if m != nil {
		return m.K
	}
	return ""
}

func (m *SiteMessage) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *SiteMessage) GetCreated() *time.Time {
	if m != nil {
		return m.Created
	}
	return nil
}

// A UserMessage is a notification message for a user.
type UserMessage struct {
	// Row ID in the table.
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// UserId is a foreign key to a User ID.
	UserId int64 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// K is a key to identify the message.
	K       string `protobuf:"bytes,3,opt,name=k,proto3" json:"k,omitempty"`
	Message string `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	// Time when the message was created.
	Created              *time.Time `protobuf:"bytes,5,opt,name=created,proto3" json:"created,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *UserMessage) Reset()         { *m = UserMessage{} }
func (m *UserMessage) String() string { return proto.CompactTextString(m) }
func (*UserMessage) ProtoMessage()    {}
func (*UserMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_tables_e838647ad188493e, []int{8}
}
func (m *UserMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserMessage.Unmarshal(m, b)
}
func (m *UserMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserMessage.Marshal(b, m, deterministic)
}
func (dst *UserMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserMessage.Merge(dst, src)
}
func (m *UserMessage) XXX_Size() int {
	return xxx_messageInfo_UserMessage.Size(m)
}
func (m *UserMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_UserMessage.DiscardUnknown(m)
}

var xxx_messageInfo_UserMessage proto.InternalMessageInfo

func (m *UserMessage) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UserMessage) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *UserMessage) GetK() string {
	if m != nil {
		return m.K
	}
	return ""
}

func (m *UserMessage) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *UserMessage) GetCreated() *time.Time {
	if m != nil {
		return m.Created
	}
	return nil
}

func init() {
	proto.RegisterType((*Site)(nil), "data.Site")
	proto.RegisterType((*Blob)(nil), "data.Blob")
	proto.RegisterType((*Content)(nil), "data.Content")
	proto.RegisterType((*User)(nil), "data.User")
	proto.RegisterType((*UserMeta)(nil), "data.UserMeta")
	proto.RegisterType((*Option)(nil), "data.Option")
	proto.RegisterType((*Media)(nil), "data.Media")
	proto.RegisterType((*SiteMessage)(nil), "data.SiteMessage")
	proto.RegisterType((*UserMessage)(nil), "data.UserMessage")
}

func init() { proto.RegisterFile("data/tables.proto", fileDescriptor_tables_e838647ad188493e) }

var fileDescriptor_tables_e838647ad188493e = []byte{
	// 643 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x54, 0xcf, 0x6f, 0xd3, 0x4a,
	0x10, 0x96, 0x63, 0xc7, 0x4e, 0x26, 0x7d, 0x4f, 0x7d, 0xab, 0x3e, 0x6a, 0x81, 0x90, 0xaa, 0xf0,
	0x43, 0x3d, 0x35, 0x12, 0x5c, 0x38, 0x17, 0x2e, 0x3d, 0x54, 0x48, 0xa6, 0x5c, 0xb8, 0x54, 0x9b,
	0xec, 0x34, 0x5d, 0x65, 0xed, 0xb5, 0xbc, 0xeb, 0x42, 0x39, 0x22, 0xfe, 0x08, 0x6e, 0x9c, 0xf9,
	0x1f, 0xf8, 0xe3, 0xd0, 0xcc, 0xda, 0x21, 0x25, 0x0d, 0x97, 0xe8, 0xfb, 0xbe, 0xd9, 0x78, 0x66,
	0xbe, 0x99, 0x5d, 0xf8, 0x4f, 0x49, 0x2f, 0x67, 0x5e, 0xce, 0x0d, 0xba, 0x93, 0xba, 0xb1, 0xde,
	0x8a, 0x84, 0xa4, 0x87, 0xff, 0xfb, 0xdb, 0x1a, 0xdd, 0xcc, 0xeb, 0x12, 0xf9, 0x27, 0x04, 0xa7,
	0x5f, 0x22, 0x48, 0xde, 0x69, 0x8f, 0xe2, 0x5f, 0x18, 0x68, 0x95, 0x47, 0x47, 0xd1, 0x71, 0x5c,
	0x0c, 0xb4, 0x12, 0x0f, 0x20, 0x55, 0xb6, 0x94, 0xba, 0xca, 0x07, 0x47, 0xd1, 0xf1, 0xb8, 0xe8,
	0x98, 0x10, 0x90, 0x54, 0xb2, 0xc4, 0x3c, 0x66, 0x95, 0x31, 0x69, 0xc6, 0x2e, 0x6d, 0x9e, 0x04,
	0x8d, 0xb0, 0xc8, 0x21, 0xbb, 0x92, 0x37, 0x7a, 0x61, 0xab, 0x7c, 0xc8, 0x72, 0x4f, 0xc5, 0x3e,
	0xc4, 0xde, 0xb8, 0x3c, 0x3d, 0x8a, 0x8e, 0xff, 0x29, 0x08, 0x4e, 0x0d, 0x24, 0xa7, 0xc6, 0xce,
	0xb7, 0x6a, 0x10, 0x90, 0x34, 0xd6, 0x60, 0x57, 0x01, 0x63, 0xb1, 0x07, 0xd1, 0x8a, 0x93, 0xc7,
	0x45, 0xb4, 0x22, 0x76, 0xc3, 0x69, 0xf7, 0x8a, 0xe8, 0x46, 0x3c, 0x85, 0xac, 0xad, 0x95, 0xf4,
	0xa8, 0x38, 0xe7, 0xe4, 0x05, 0x9c, 0x70, 0xab, 0x17, 0xba, 0xc4, 0xa2, 0x0f, 0x4d, 0x7f, 0x0c,
	0x20, 0x7b, 0x6d, 0x2b, 0x8f, 0x95, 0xbf, 0x2f, 0xa3, 0xd3, 0x3e, 0x64, 0x8c, 0x0b, 0xc6, 0xac,
	0x99, 0x76, 0xd9, 0x77, 0x4c, 0x98, 0xdc, 0x91, 0xad, 0xbf, 0xb6, 0x0d, 0x27, 0x8f, 0x8b, 0x8e,
	0xd1, 0x59, 0xf2, 0xb9, 0x6b, 0x99, 0x31, 0x9d, 0xad, 0x65, 0x83, 0x95, 0xe7, 0x96, 0xe3, 0xa2,
	0x63, 0xe2, 0x00, 0x86, 0x5e, 0x7b, 0x83, 0x79, 0xc6, 0x87, 0x03, 0x11, 0x8f, 0x01, 0x4a, 0xf4,
	0xf2, 0x32, 0x84, 0x46, 0x1c, 0x1a, 0x93, 0x72, 0xc1, 0xe1, 0x47, 0xc0, 0xe4, 0x52, 0xa1, 0x5b,
	0xe4, 0x63, 0x8e, 0x8e, 0x48, 0x78, 0x83, 0x6e, 0x41, 0xd9, 0xe7, 0x56, 0xdd, 0xe6, 0xc0, 0x86,
	0x30, 0xa6, 0xec, 0xce, 0x4b, 0xdf, 0xba, 0x7c, 0x12, 0xe6, 0x18, 0xd8, 0xa6, 0x57, 0x7b, 0xbb,
	0xbd, 0xfa, 0x19, 0x41, 0xf2, 0xde, 0x61, 0xb3, 0x65, 0xd4, 0x01, 0x0c, 0x5b, 0xde, 0x83, 0x30,
	0x9b, 0x40, 0x48, 0xc5, 0x52, 0x6a, 0xd3, 0x79, 0x15, 0x08, 0x95, 0x55, 0x4b, 0xe7, 0xba, 0x39,
	0x31, 0xa6, 0x93, 0x57, 0xfc, 0xff, 0xe0, 0x54, 0x20, 0xa4, 0x1a, 0x56, 0xd3, 0xa0, 0x9a, 0x7e,
	0xbd, 0x78, 0x0d, 0xb2, 0x8d, 0x35, 0xd8, 0x28, 0x7f, 0xb4, 0xbb, 0x7c, 0x84, 0x11, 0x55, 0x7f,
	0x8e, 0x5e, 0x8a, 0x43, 0xc8, 0x5a, 0x87, 0xcd, 0xe5, 0xba, 0x8d, 0x94, 0xe8, 0x99, 0x0a, 0x1b,
	0x15, 0xda, 0xe8, 0x37, 0x2a, 0xbe, 0x67, 0xa3, 0x92, 0xdd, 0x69, 0x5e, 0x41, 0xfa, 0xb6, 0xf6,
	0xda, 0x56, 0xeb, 0xfd, 0x89, 0x36, 0xf6, 0xe7, 0x2f, 0xdf, 0x9f, 0x7e, 0x8f, 0x60, 0x78, 0x8e,
	0x4a, 0xcb, 0x0d, 0x83, 0xc7, 0x6c, 0xf0, 0x3e, 0xc4, 0xf8, 0xc9, 0x77, 0xff, 0x23, 0xb8, 0xfe,
	0x76, 0x7c, 0x77, 0x37, 0xd9, 0xaf, 0x64, 0xe3, 0x36, 0xee, 0x43, 0x2c, 0x8d, 0xef, 0x8c, 0x25,
	0x48, 0xa7, 0x78, 0x5f, 0x82, 0xab, 0x8c, 0xc5, 0x73, 0x18, 0xb5, 0xb5, 0xb1, 0x52, 0xa1, 0x62,
	0x63, 0xef, 0xb6, 0xb6, 0x8e, 0x4d, 0xbf, 0x45, 0x30, 0xa1, 0x07, 0xe2, 0x1c, 0x9d, 0x93, 0xcb,
	0xed, 0x77, 0xe2, 0x10, 0x32, 0xaa, 0x84, 0x6c, 0x0d, 0x97, 0x26, 0x25, 0x7a, 0xf6, 0xfb, 0xf2,
	0xc6, 0x7f, 0x5e, 0xde, 0xa4, 0xb7, 0x22, 0x87, 0xac, 0x0c, 0x5f, 0xed, 0x9f, 0x88, 0x8e, 0x92,
	0xed, 0x8b, 0x06, 0xd9, 0xf6, 0x74, 0xdb, 0xf6, 0x2e, 0x34, 0xfd, 0x1a, 0xc1, 0x24, 0x8c, 0x77,
	0x67, 0x69, 0xfd, 0xc4, 0x07, 0xdb, 0x13, 0x8f, 0xef, 0x29, 0x23, 0xd9, 0x59, 0xc6, 0x70, 0x67,
	0x19, 0xa7, 0xcf, 0x3e, 0x3c, 0x59, 0x6a, 0x7f, 0xdd, 0xce, 0x4f, 0x16, 0xb6, 0x9c, 0xa9, 0xc5,
	0x35, 0x56, 0xab, 0x59, 0x29, 0x3f, 0xe3, 0x47, 0xdd, 0xe0, 0xac, 0x5e, 0x2d, 0x67, 0xf4, 0x00,
	0xcf, 0x53, 0x7e, 0x70, 0x5f, 0xfe, 0x0a, 0x00, 0x00, 0xff, 0xff, 0x6f, 0x5e, 0x6c, 0xe5, 0xa2,
	0x05, 0x00, 0x00,
}
