// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hooks/payloads/payloads.proto

package payloads

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Custom is a container for payloads used by all custom hooks.
type Custom struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Custom) Reset()         { *m = Custom{} }
func (m *Custom) String() string { return proto.CompactTextString(m) }
func (*Custom) ProtoMessage()    {}
func (*Custom) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4410b8b59b355ba, []int{0}
}

func (m *Custom) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Custom.Unmarshal(m, b)
}
func (m *Custom) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Custom.Marshal(b, m, deterministic)
}
func (m *Custom) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Custom.Merge(m, src)
}
func (m *Custom) XXX_Size() int {
	return xxx_messageInfo_Custom.Size(m)
}
func (m *Custom) XXX_DiscardUnknown() {
	xxx_messageInfo_Custom.DiscardUnknown(m)
}

var xxx_messageInfo_Custom proto.InternalMessageInfo

func (m *Custom) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*Custom)(nil), "payloads.Custom")
}

func init() { proto.RegisterFile("hooks/payloads/payloads.proto", fileDescriptor_d4410b8b59b355ba) }

var fileDescriptor_d4410b8b59b355ba = []byte{
	// 120 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0xcd, 0xc8, 0xcf, 0xcf,
	0x2e, 0xd6, 0x2f, 0x48, 0xac, 0xcc, 0xc9, 0x4f, 0x4c, 0x41, 0x30, 0xf4, 0x0a, 0x8a, 0xf2, 0x4b,
	0xf2, 0x85, 0x38, 0x60, 0x7c, 0x25, 0x19, 0x2e, 0x36, 0xe7, 0xd2, 0xe2, 0x92, 0xfc, 0x5c, 0x21,
	0x21, 0x2e, 0x96, 0x94, 0xc4, 0x92, 0x44, 0x09, 0x46, 0x05, 0x46, 0x0d, 0x9e, 0x20, 0x30, 0xdb,
	0x49, 0x3f, 0x4a, 0x37, 0x3d, 0xb3, 0x24, 0xa3, 0x34, 0x49, 0x2f, 0x39, 0x3f, 0x57, 0x3f, 0x25,
	0x39, 0x23, 0x35, 0x2f, 0x5b, 0x3f, 0x37, 0xb1, 0x2a, 0xb5, 0x3c, 0xb3, 0x28, 0x55, 0xbf, 0x20,
	0x3b, 0x5d, 0x1f, 0xd5, 0x9e, 0x24, 0x36, 0xb0, 0xf9, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff,
	0xf4, 0x76, 0x45, 0xca, 0x80, 0x00, 0x00, 0x00,
}
