// Code generated by protoc-gen-go. DO NOT EDIT.
// source: types/time/time.proto

package time

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// A Time is a point in time, represented as the number of seconds and nanoseconds
// since the Unix Epoch of January 1, 1970 UTC.
//
// The valid range is from 0001-01-01T00:00:00Z to 9999-12-31T23:59:59.999999999Z.
type Time struct {
	// Seconds is the number of seconds since 1970-01-01T00:00:00Z.
	Seconds int64 `protobuf:"varint,1,opt,name=seconds,proto3" json:"seconds,omitempty"`
	// Nanos is the number of nanoseconds since the time identified by the seconds.
	// Negative second values with fractions must still have non-negative nanos values
	// that count forward in time. The valid range is from 0 to 999,999,999, inclusive.
	Nanos                int32    `protobuf:"varint,2,opt,name=nanos,proto3" json:"nanos,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Time) Reset()         { *m = Time{} }
func (m *Time) String() string { return proto.CompactTextString(m) }
func (*Time) ProtoMessage()    {}
func (*Time) Descriptor() ([]byte, []int) {
	return fileDescriptor_83bb15a3eb453019, []int{0}
}

func (m *Time) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Time.Unmarshal(m, b)
}
func (m *Time) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Time.Marshal(b, m, deterministic)
}
func (m *Time) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Time.Merge(m, src)
}
func (m *Time) XXX_Size() int {
	return xxx_messageInfo_Time.Size(m)
}
func (m *Time) XXX_DiscardUnknown() {
	xxx_messageInfo_Time.DiscardUnknown(m)
}

var xxx_messageInfo_Time proto.InternalMessageInfo

func (m *Time) GetSeconds() int64 {
	if m != nil {
		return m.Seconds
	}
	return 0
}

func (m *Time) GetNanos() int32 {
	if m != nil {
		return m.Nanos
	}
	return 0
}

func init() {
	proto.RegisterType((*Time)(nil), "time.Time")
}

func init() { proto.RegisterFile("types/time/time.proto", fileDescriptor_83bb15a3eb453019) }

var fileDescriptor_83bb15a3eb453019 = []byte{
	// 135 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2d, 0xa9, 0x2c, 0x48,
	0x2d, 0xd6, 0x2f, 0xc9, 0xcc, 0x4d, 0x05, 0x13, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0x2c,
	0x20, 0xb6, 0x92, 0x19, 0x17, 0x4b, 0x48, 0x66, 0x6e, 0xaa, 0x90, 0x04, 0x17, 0x7b, 0x71, 0x6a,
	0x72, 0x7e, 0x5e, 0x4a, 0xb1, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x73, 0x10, 0x8c, 0x2b, 0x24, 0xc2,
	0xc5, 0x9a, 0x97, 0x98, 0x97, 0x5f, 0x2c, 0xc1, 0xa4, 0xc0, 0xa8, 0xc1, 0x1a, 0x04, 0xe1, 0x38,
	0x69, 0x47, 0x69, 0xa6, 0x67, 0x96, 0x64, 0x94, 0x26, 0xe9, 0x25, 0xe7, 0xe7, 0xea, 0xa7, 0x24,
	0x67, 0xa4, 0xe6, 0x65, 0xeb, 0xe7, 0x26, 0x56, 0xa5, 0x96, 0x67, 0x16, 0xa5, 0xea, 0x17, 0x64,
	0xa7, 0xeb, 0x23, 0x6c, 0x4d, 0x62, 0x03, 0xdb, 0x68, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0xfb,
	0xdc, 0x2c, 0x78, 0x8a, 0x00, 0x00, 0x00,
}
