// Code generated by protoc-gen-go. DO NOT EDIT.
// source: room/special/special.proto

package special // import "github.com/dchenk/mazewire/pkg/room/special"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// The PageCSS type is used to combine the data of a bytes.Buffer (embedded as private) with a
// list of names of modules whose CSS code has already been written to the buffer.
type PageCSS struct {
	Code                 []byte   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	WrittenModules       []string `protobuf:"bytes,2,rep,name=written_modules,json=writtenModules,proto3" json:"written_modules,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PageCSS) Reset()         { *m = PageCSS{} }
func (m *PageCSS) String() string { return proto.CompactTextString(m) }
func (*PageCSS) ProtoMessage()    {}
func (*PageCSS) Descriptor() ([]byte, []int) {
	return fileDescriptor_special_a10678d0765875bc, []int{0}
}
func (m *PageCSS) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PageCSS.Unmarshal(m, b)
}
func (m *PageCSS) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PageCSS.Marshal(b, m, deterministic)
}
func (dst *PageCSS) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PageCSS.Merge(dst, src)
}
func (m *PageCSS) XXX_Size() int {
	return xxx_messageInfo_PageCSS.Size(m)
}
func (m *PageCSS) XXX_DiscardUnknown() {
	xxx_messageInfo_PageCSS.DiscardUnknown(m)
}

var xxx_messageInfo_PageCSS proto.InternalMessageInfo

func (m *PageCSS) GetCode() []byte {
	if m != nil {
		return m.Code
	}
	return nil
}

func (m *PageCSS) GetWrittenModules() []string {
	if m != nil {
		return m.WrittenModules
	}
	return nil
}

func init() {
	proto.RegisterType((*PageCSS)(nil), "special.PageCSS")
}

func init() { proto.RegisterFile("room/special/special.proto", fileDescriptor_special_a10678d0765875bc) }

var fileDescriptor_special_a10678d0765875bc = []byte{
	// 152 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2a, 0xca, 0xcf, 0xcf,
	0xd5, 0x2f, 0x2e, 0x48, 0x4d, 0xce, 0x4c, 0xcc, 0x81, 0xd1, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9,
	0x42, 0xec, 0x50, 0xae, 0x92, 0x1b, 0x17, 0x7b, 0x40, 0x62, 0x7a, 0xaa, 0x73, 0x70, 0xb0, 0x90,
	0x10, 0x17, 0x4b, 0x72, 0x7e, 0x4a, 0xaa, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x4f, 0x10, 0x98, 0x2d,
	0xa4, 0xce, 0xc5, 0x5f, 0x5e, 0x94, 0x59, 0x52, 0x92, 0x9a, 0x17, 0x9f, 0x9b, 0x9f, 0x52, 0x9a,
	0x93, 0x5a, 0x2c, 0xc1, 0xa4, 0xc0, 0xac, 0xc1, 0x19, 0xc4, 0x07, 0x15, 0xf6, 0x85, 0x88, 0x3a,
	0xe9, 0x46, 0x69, 0xa7, 0x67, 0x96, 0x64, 0x94, 0x26, 0xe9, 0x25, 0xe7, 0xe7, 0xea, 0xa7, 0x24,
	0x67, 0xa4, 0xe6, 0x65, 0xeb, 0xe7, 0x26, 0x56, 0xa5, 0x96, 0x67, 0x16, 0xa5, 0xea, 0x17, 0x64,
	0xa7, 0xeb, 0x23, 0xbb, 0x26, 0x89, 0x0d, 0xec, 0x0c, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x82, 0x06, 0x0e, 0x2e, 0xa4, 0x00, 0x00, 0x00,
}
