// Code generated by protoc-gen-go. DO NOT EDIT.
// source: filters/payloads/payloads.proto

package payloads // import "github.com/dchenk/mazewire/pkg/filters/payloads"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Custom is a container for payloads used by all custom hooks.
type Custom struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Custom) Reset()         { *m = Custom{} }
func (m *Custom) String() string { return proto.CompactTextString(m) }
func (*Custom) ProtoMessage()    {}
func (*Custom) Descriptor() ([]byte, []int) {
	return fileDescriptor_payloads_94b69908b04b253c, []int{0}
}
func (m *Custom) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Custom.Unmarshal(m, b)
}
func (m *Custom) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Custom.Marshal(b, m, deterministic)
}
func (dst *Custom) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Custom.Merge(dst, src)
}
func (m *Custom) XXX_Size() int {
	return xxx_messageInfo_Custom.Size(m)
}
func (m *Custom) XXX_DiscardUnknown() {
	xxx_messageInfo_Custom.DiscardUnknown(m)
}

var xxx_messageInfo_Custom proto.InternalMessageInfo

func (m *Custom) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

// UserCSS is the payload given to hook handlers of the UserCSS hook.
type UserCSS struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserCSS) Reset()         { *m = UserCSS{} }
func (m *UserCSS) String() string { return proto.CompactTextString(m) }
func (*UserCSS) ProtoMessage()    {}
func (*UserCSS) Descriptor() ([]byte, []int) {
	return fileDescriptor_payloads_94b69908b04b253c, []int{1}
}
func (m *UserCSS) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserCSS.Unmarshal(m, b)
}
func (m *UserCSS) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserCSS.Marshal(b, m, deterministic)
}
func (dst *UserCSS) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserCSS.Merge(dst, src)
}
func (m *UserCSS) XXX_Size() int {
	return xxx_messageInfo_UserCSS.Size(m)
}
func (m *UserCSS) XXX_DiscardUnknown() {
	xxx_messageInfo_UserCSS.DiscardUnknown(m)
}

var xxx_messageInfo_UserCSS proto.InternalMessageInfo

func (m *UserCSS) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

// UserJS is the payload given to hook handlers of the UserJS hook.
type UserJS struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserJS) Reset()         { *m = UserJS{} }
func (m *UserJS) String() string { return proto.CompactTextString(m) }
func (*UserJS) ProtoMessage()    {}
func (*UserJS) Descriptor() ([]byte, []int) {
	return fileDescriptor_payloads_94b69908b04b253c, []int{2}
}
func (m *UserJS) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserJS.Unmarshal(m, b)
}
func (m *UserJS) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserJS.Marshal(b, m, deterministic)
}
func (dst *UserJS) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserJS.Merge(dst, src)
}
func (m *UserJS) XXX_Size() int {
	return xxx_messageInfo_UserJS.Size(m)
}
func (m *UserJS) XXX_DiscardUnknown() {
	xxx_messageInfo_UserJS.DiscardUnknown(m)
}

var xxx_messageInfo_UserJS proto.InternalMessageInfo

func (m *UserJS) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func init() {
	proto.RegisterType((*Custom)(nil), "payloads.Custom")
	proto.RegisterType((*UserCSS)(nil), "payloads.UserCSS")
	proto.RegisterType((*UserJS)(nil), "payloads.UserJS")
}

func init() {
	proto.RegisterFile("filters/payloads/payloads.proto", fileDescriptor_payloads_94b69908b04b253c)
}

var fileDescriptor_payloads_94b69908b04b253c = []byte{
	// 151 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x4f, 0xcb, 0xcc, 0x29,
	0x49, 0x2d, 0x2a, 0xd6, 0x2f, 0x48, 0xac, 0xcc, 0xc9, 0x4f, 0x4c, 0x41, 0x30, 0xf4, 0x0a, 0x8a,
	0xf2, 0x4b, 0xf2, 0x85, 0x38, 0x60, 0x7c, 0x25, 0x19, 0x2e, 0x36, 0xe7, 0xd2, 0xe2, 0x92, 0xfc,
	0x5c, 0x21, 0x21, 0x2e, 0x96, 0x94, 0xc4, 0x92, 0x44, 0x09, 0x46, 0x05, 0x46, 0x0d, 0x9e, 0x20,
	0x30, 0x5b, 0x49, 0x96, 0x8b, 0x3d, 0xb4, 0x38, 0xb5, 0xc8, 0x39, 0x38, 0x18, 0x24, 0x9d, 0x9c,
	0x9f, 0x92, 0x0a, 0x96, 0xe6, 0x0c, 0x02, 0xb3, 0x41, 0x9a, 0x41, 0xd2, 0x5e, 0x58, 0x65, 0x9d,
	0x0c, 0xa3, 0xf4, 0xd3, 0x33, 0x4b, 0x32, 0x4a, 0x93, 0xf4, 0x92, 0xf3, 0x73, 0xf5, 0x53, 0x92,
	0x33, 0x52, 0xf3, 0xb2, 0xf5, 0x73, 0x13, 0xab, 0x52, 0xcb, 0x33, 0x8b, 0x52, 0xf5, 0x0b, 0xb2,
	0xd3, 0xf5, 0xd1, 0x9d, 0x99, 0xc4, 0x06, 0x76, 0x9e, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0xe2,
	0xc4, 0xfd, 0x91, 0xc1, 0x00, 0x00, 0x00,
}
